managecfshop/Controllers/ABCsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using coffeeShop.Models;
using managecfshop.Data;

namespace managecfshop.Controllers
{
    public class ABCsController : Controller
    {
        private managecfshopContext db = new managecfshopContext();

        // GET: ABCs
        public ActionResult Index()
        {
            return View(db.ABCs.ToList());
        }

        // GET: ABCs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ABC aBC = db.ABCs.Find(id);
            if (aBC == null)
            {
                return HttpNotFound();
            }
            return View(aBC);
        }

        // GET: ABCs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ABCs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserName,Status,Time")] ABC aBC)
        {
            if (ModelState.IsValid)
            {
                db.ABCs.Add(aBC);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aBC);
        }

        // GET: ABCs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ABC aBC = db.ABCs.Find(id);
            if (aBC == null)
            {
                return HttpNotFound();
            }
            return View(aBC);
        }

        // POST: ABCs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserName,Status,Time")] ABC aBC)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aBC).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aBC);
        }

        // GET: ABCs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ABC aBC = db.ABCs.Find(id);
            if (aBC == null)
            {
                return HttpNotFound();
            }
            return View(aBC);
        }

        // POST: ABCs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ABC aBC = db.ABCs.Find(id);
            db.ABCs.Remove(aBC);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

managecfshop/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using coffeeShop.Models;
using managecfshop.Data;

namespace managecfshop.Controllers
{
    public class AccountsController : Controller
    {
        private managecfshopContext db = new managecfshopContext();
           public ActionResult Index()
            {
                return View(db.Accounts.ToList());
            }

            // GET: Accounts/Details/5
            public ActionResult Details(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Account account = db.Accounts.Find(id);
                if (account == null)
                {
                    return HttpNotFound();
                }
                return View(account);
            }

            // GET: Accounts/Create
            public ActionResult Create()
            {
                return View();
            }

            // POST: Accounts/Create
            // To protect from overposting attacks, enable the specific properties you want to bind to, for 
            // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Create([Bind(Include = "Id,Email,Password")] Account account)
            {
                if (ModelState.IsValid)
                {
                    db.Accounts.Add(account);
                    db.SaveChanges();
                    return RedirectToAction("Register", "Account");
                }

                return View(account);
            }
        public ActionResult Login([Bind(Include = "Id,Email,Password")] Account accounts)
        {
            if (ModelState.IsValid)
            {
                foreach (var account in db.Accounts.ToList())
                {
                    if ((accounts.Email == account.Email) || (accounts.Email == "n.kimanh1099@gmail.com"))
                    {
                        return RedirectToAction("_LoginPartial", "Shared");
                    }
                }
                db.ABCs.Add(
                                 new ABC { UserName = accounts.Email, Status = "log off", Time = DateTime.Now });
                db.SaveChanges();
                if (accounts.Email == "n.kimanh1099@gmail.com")
                {
                    return RedirectToAction("_Layout_admin", "Shared");
                }
                else
                {
                    return RedirectToAction("_Layout_employ", "Shared");
                }
            }

            return View(accounts);
        }

        // GET: Accounts/Edit/5
        public ActionResult Edit(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Account account = db.Accounts.Find(id);
                if (account == null)
                {
                    return HttpNotFound();
                }
                return View(account);
            }

            // POST: Accounts/Edit/5
            // To protect from overposting attacks, enable the specific properties you want to bind to, for 
            // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public ActionResult Edit([Bind(Include = "Id,Email,Password")] Account account)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(account).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(account);
            }

            // GET: Accounts/Delete/5
            public ActionResult Delete(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Account account = db.Accounts.Find(id);
                if (account == null)
                {
                    return HttpNotFound();
                }
                return View(account);
            }

            // POST: Accounts/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public ActionResult DeleteConfirmed(int id)
            {
                Account account = db.Accounts.Find(id);
                db.Accounts.Remove(account);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            protected override void Dispose(bool disposing)
            {
                if (disposing)
                {
                    db.Dispose();
                }
                base.Dispose(disposing);
            }
        }
    }

managecfshop/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ManageCoffeeShop.Models;
using managecfshop.Data;

namespace managecfshop.Controllers
{
    public class BillsController : Controller
    {
        private managecfshopContext db = new managecfshopContext();

        // GET: Bills
        public ActionResult Index()
        {
            return View(db.Bills.ToList());
        }

        // GET: Bills/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // GET: Bills/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Bills/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DateCheckIn,DateCheckOut,IdTable,TotalPrice")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                db.Bills.Add(bill);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bill);
        }

        // GET: Bills/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // POST: Bills/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DateCheckIn,DateCheckOut,IdTable,TotalPrice")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bill);
        }

        // GET: Bills/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bill bill = db.Bills.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // POST: Bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bill bill = db.Bills.Find(id);
            db.Bills.Remove(bill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

managecfshop/Views/Shared/_Layout - Copy.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<coffeeShop.Models.Login>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>@ViewBag.Title - Coffee Shop</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar-black navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar">j</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img style="height:50px;width:50px" src="~/coffee-shop/logo.png" />
                @Html.ActionLink("Coffee Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @foreach (var item in Model)
    {
        if ((item.Email) == "n.kimanh1099@gmail.com")
        {
            <!-- Sidebar -->
            <div class=" navbar-inverse ">
                <div class="w3-sidebar w3-light-gray w3-bar-block" style="width:20%;background-color:darkgray;color:white;font-weight:200;height:100%">
                    <ul>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Login Histories", "Index", "ABCs", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Bill Information", "Index", "BillInfors", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Categories", "Index", "Categories", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Menu", "Index", "SelectMenus", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Table", "Index", "Tables", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Bill", "Index", "Bills", null, new { style = "color:black" })</li>

                    </ul>
                </div>
            </div>
            <div class="container body-content" style="margin-left: 20%; width: 80%; margin-bottom: 0">
                @RenderBody()
                <hr />
                <footer>
                    <p style="margin-top:300px">&copy; @DateTime.Now.Year - Coffee Shop</p>
                </footer>
            </div>
        }
        else if ((item.Email) == "")
        {
            <!-- Sidebar -->
            <div class=" navbar-inverse ">
                <div class="w3-sidebar w3-light-blue w3-bar-block" style="width:20%;background-color:darkgray;color:white;font-weight:200;height:100%">
                    <ul>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Bill Information", "Index", "BillInfors", null, new { style = "color:black;font-weight:50px" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Categories", "Index", "Categories", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Menu", "Index", "SelectMenus", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Table", "Index", "Tables", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Bill", "Index", "Bills", null, new { style = "color:black" })</li>

                    </ul>
                </div>
            </div>
            <div class="container body-content" style="margin-left: 20%; width: 80%; margin-bottom: 0">
                @RenderBody()
                <hr />
                <footer>
                    <p style="margin-top:300px">&copy; @DateTime.Now.Year - Coffee Shop</p>
                </footer>
            </div>
        }

        else
         {
        <div class="container body-content">
        @RenderBody()
            <hr />
        <footer>
            <p style = "margin-top:300px" > &copy; @DateTime.Now.Year - Coffee Shop</p>
        </footer>
        </div>
        }
}
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>

</html>

managecfshop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>@ViewBag.Title - Coffee-Shop</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar-black navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar">j</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img style="height:50px;width:50px" src="~/coffee-shop/logo.png" />
                @Html.ActionLink("Coffee Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    
            <!-- Sidebar -->
            <div class=" navbar-inverse ">
                <div class="w3-sidebar w3-light-gray w3-bar-block" style="width:20%;background-color:darkgray;color:white;font-weight:200;height:100%">
                    <ul>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Login Histories", "Index", "ABCs", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Bill Information", "Index", "BillInfors", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Categories", "Index", "Categories", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Menu", "Index", "SelectMenus", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Table", "Index", "Tables", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Bill", "Index", "Bills", null, new { style = "color:black" })</li>

                    </ul>
                </div>
            </div>

        <div class="container body-content" style="margin-left: 20%; width: 80%; margin-bottom: 0">
            @RenderBody()
            <hr />
            <footer>
                <p style="margin-top:300px">&copy; @DateTime.Now.Year - Coffee Shop</p>
            </footer>
        </div>
   
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>

</html>

managecfshop/Views/Shared/_Layout_admin.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>@ViewBag.Title - Coffee-Shop</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar-black navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar">j</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img style="height:50px;width:50px" src="~/coffee-shop/logo.png" />
                @Html.ActionLink("Coffee Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @Html.ActionLink("Hello Admin " + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                    </li>
                    <li>@Html.ActionLink("Manage", "Index", "Accounts", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                    <li>>@Html.ActionLink("Log Off", "_Layout")</li>
                </ul>
            </div>
        </div>
    </div>
  <!-- Sidebar -->
            <div class=" navbar-inverse ">
                <div class="w3-sidebar w3-light-gray w3-bar-block" style="width:20%;background-color:darkgray;color:white;font-weight:200;height:100%">
                    <ul>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Login Histories", "Index", "ABCs", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Bill Information", "Index", "BillInfors", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Categories", "Index", "Categories", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Menu", "Index", "SelectMenus", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Table", "Index", "Tables", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Bill", "Index", "Bills", null, new { style = "color:black" })</li>

                    </ul>
                </div>
            </div>
    
        <div class="container body-content" style="margin-left: 20%; width: 80%; margin-bottom: 0">
            <img src="~/coffee-shop/nhanvien1.jpg" />
            <hr />
            <footer>
                <p style="margin-top:300px">&copy; @DateTime.Now.Year - Coffee Shop</p>
            </footer>
        </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>

</html>

managecfshop/Views/Shared/_Layout_employ.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>@ViewBag.Title - Coffee-Shop</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar-black navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar">j</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img style="height:50px;width:50px" src="~/coffee-shop/logo.png" />
                @Html.ActionLink("Coffee Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
                <li>>@Html.ActionLink("Log Off", "_Layout")</li>
            </div>
        </div>
    </div>
 
            <!-- Sidebar -->
            <div class=" navbar-inverse ">
                <div class="w3-sidebar w3-light-gray w3-bar-block" style="width:20%;background-color:darkgray;color:white;font-weight:200;height:100%">
                    <ul>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Bill Information", "Index", "BillInfors", null, new { style = "color:black;font-weight:50px" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Categories", "Index", "Categories", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Menu", "Index", "SelectMenus", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Table", "Index", "Tables", null, new { style = "color:black" })</li>
                        <li class="w3-bar-item w3-button" onclick="openLink(event, 'Fade')">@Html.ActionLink("Bill", "Index", "Bills", null, new { style = "color:black" })</li>

                    </ul>
                </div>
            </div>
            <div class="container body-content" style="margin-left: 20%; width: 80%; margin-bottom: 0">
                <img src="~/coffee-shop/nhanvien1.jpg" />
                <hr />
                <footer>
                    <p style="margin-top:300px">&copy; @DateTime.Now.Year - Coffee Shop</p>
                </footer>
            </div>
  
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>

</html>